theme: light

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: "*.local.host"
      policy: one_factor

session:
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 15m
  # Redis configuration
  redis:
    host: redis
    port: 6379
  cookies:
    - domain: 'local.host'
      authelia_url: 'https://auth.local.host'
      default_redirection_url: 'https://openwebui.local.host'

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt